import {
  Ban,
  Battery,
  BatteryLow,
  Bot,
  Check,
  ChevronDown,
  ChevronRight,
  CircleCheck,
  CircleDashed,
  CircleHelp,
  CircleX,
  Clock,
  Cpu,
  Download,
  Ellipsis,
  Eye,
  FlaskConical,
  GitBranch,
  Globe,
  Hash,
  House,
  Info,
  Languages,
  Layers,
  Lightbulb,
  ListChecks,
  ListFilter,
  LoaderCircle,
  Lock,
  type LucideIcon,
  Map as MapGlyph,
  Minus,
  NotebookText,
  OctagonX,
  Play,
  Plus,
  Radar,
  Radio,
  RotateCcw,
  Route,
  ShieldAlert,
  Signal,
  SignalZero,
  Sparkles,
  Square,
  Target,
  TestTubeDiagonal,
  TriangleAlert,
  Users,
  WifiOff,
  X,
} from "lucide-react"

export const ICONS = {
  close: X,
  check: Check,
  alert: TriangleAlert,
  critical: OctagonX,
  info: Info,
  play: Play,
  stop: Square,
  retry: RotateCcw,
  download: Download,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  battery: Battery,
  "battery-low": BatteryLow,
  signal: Signal,
  "signal-off": SignalZero,
  clock: Clock,
  target: Target,
  sample: FlaskConical,
  map: MapGlyph,
  robot: Bot,
  hazard: ShieldAlert,
  sensor: Radar,
  plan: ListChecks,
  journal: NotebookText,
  hypothesis: Lightbulb,
  confirmed: CircleCheck,
  refuted: CircleX,
  inconclusive: CircleHelp,
  team: Users,
  language: Languages,
  live: Radio,
  offline: WifiOff,
  loader: LoaderCircle,
  home: House,
  route: Route,
  filter: ListFilter,
  pending: CircleDashed,
  observation: Eye,
  experiment: TestTubeDiagonal,
  decision: GitBranch,
  llm: Sparkles,
  fallback: Cpu,
  terrain: Layers,
  reservation: Lock,
  seed: Hash,
  minus: Minus,
  plus: Plus,
  more: Ellipsis,
  dropped: Ban,
  globe: Globe,
} as const satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICONS
